# Generated by Django 5.2.9 on 2026-02-14 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_contact', to='clients.client'),
        ),
    ]
