# Generated by Django 5.2.9 on 2026-02-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('pending', 'Pendiente'), ('closed', 'Cerrados')], default='normal', max_length=20, verbose_name='Estado'),
        ),
    ]
