# Generated by Django 5.2.9 on 2026-03-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_conversation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickreply',
            name='shortcut',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Atajo / Código'),
        ),
    ]
