# Generated by Django 5.2.9 on 2026-03-10 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_internal_notes'),
        ('communications', '0003_quickreply_shortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_contact', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('normal', 'Activo'), ('pending', 'Pendiente'), ('closed', 'Cerrado')], default='normal', max_length=20, verbose_name='Estado'),
        ),
    ]
