# Generated by Django 5.2.9 on 2026-03-11 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_conversation_options_emailaccount_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='users',
            field=models.ManyToManyField(related_name='email_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
    ]
