# Generated by Django 5.2.9 on 2026-03-14 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_alter_contact_client_alter_conversation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Menú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('trigger_keywords', models.JSONField(blank=True, default=list, help_text='Lista de palabras que activan el menú (ej: hola, buenas, inicio)', verbose_name='Palabras Clave')),
                ('greeting_text', models.TextField(help_text='Texto que se muestra antes de las opciones', verbose_name='Texto de Bienvenida')),
                ('footer_text', models.CharField(blank=True, default='Responda con el número de su elección', max_length=255, null=True, verbose_name='Texto al Pie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menú de Bienvenida',
                'verbose_name_plural': 'Menús de Bienvenida',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMenuState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_state', to='communications.contact')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.welcomemenu')),
            ],
            options={
                'verbose_name': 'Estado de Menú',
                'verbose_name_plural': 'Estados de Menú',
            },
        ),
        migrations.CreateModel(
            name='WelcomeMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número de Opción')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='communications.welcomemenu')),
            ],
            options={
                'verbose_name': 'Opción de Menú',
                'verbose_name_plural': 'Opciones de Menú',
                'ordering': ['number'],
                'unique_together': {('menu', 'number')},
            },
        ),
    ]
