# Generated by Django 5.2.4 on 2026-03-15 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_welcomemenu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('normal', 'Activo'), ('assigned', 'Asignada'), ('pending', 'Pendiente'), ('closed', 'Cerrado')], default='normal', max_length=20, verbose_name='Estado'),
        ),
    ]
