# Generated by Django 5.2.4 on 2026-03-17 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_remove_emailaccount_users_emailaccount_user'),
        ('communications', '0007_conversation_user'),
    ]

    operations = [
    ]
