# Generated by Django 5.2.4 on 2026-04-15 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_conversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='email_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queued_email', to='communications.emailmessage'),
        ),
    ]
