# Generated by Django 5.2.4 on 2026-04-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_emailqueue_email_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/'),
        ),
    ]
