# Generated by Django 5.2.4 on 2026-05-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_internalchatmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='internalchatmessage',
            new_name='communicati_created_288917_idx',
            old_name='communications_created_at_idx',
        ),
    ]
