# Generated by Django 5.2.4 on 2026-05-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0011_rename_communications_created_at_idx_communicati_created_288917_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='imap_uid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IMAP UID'),
        ),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together={('email_account', 'imap_uid')},
        ),
    ]
