# Generated by Django 5.2.4 on 2026-05-15 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0012_emailmessage_imap_uid_and_more'),
        ('communications', '0012_internalchatmessage_file_fields'),
    ]

    operations = [
    ]
