# Generated by Django 5.2.4 on 2026-05-15 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0013_merge_20260514_2259'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='internalchatreadstate',
            new_name='communicati_last_re_df054f_idx',
            old_name='communications_last_read_at_idx',
        ),
    ]
