# Generated by Django 5.2.4 on 2026-05-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0014_rename_communications_last_read_at_idx_communicati_last_re_df054f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Programado para'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='send_error',
            field=models.TextField(blank=True, null=True, verbose_name='Error de envío'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Falló')], default='draft', max_length=20, verbose_name='Estado'),
        ),
    ]
