# Generated by Django 5.2.4 on 2026-05-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0015_emailmessage_scheduled_at_emailmessage_send_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='send_error',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='sent_at',
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('received', 'Recibido'), ('queued', 'En cola'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='received', max_length=20),
        ),
    ]
