# Generated by Django 5.2.4 on 2026-05-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0016_remove_emailmessage_scheduled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='status',
        ),
    ]
