# Generated by Django 5.2.4 on 2026-05-26 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0017_remove_emailmessage_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conversation',
            name='email_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='communications.emailaccount'),
        ),
        migrations.AddField(
            model_name='emailthread',
            name='email_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='communications.emailaccount'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='email_message_id',
            field=models.CharField(max_length=255, verbose_name='Message-ID'),
        ),
        migrations.AddConstraint(
            model_name='emailmessage',
            constraint=models.UniqueConstraint(fields=('email_account', 'imap_uid'), name='unique_imap_uid_per_account'),
        ),
        migrations.AddConstraint(
            model_name='emailmessage',
            constraint=models.UniqueConstraint(fields=('email_account', 'email_message_id'), name='unique_message_id_per_account'),
        ),
    ]
