# Generated by Django 5.2.4 on 2026-05-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0018_alter_emailmessage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='email_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Email'),
        ),
    ]
