# Generated by Django 5.2.4 on 2026-05-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0019_emailmessage_email_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.JSONField(blank=True, default=list, verbose_name='Participantes'),
        ),
    ]
