# Generated by Django 5.2.4 on 2026-06-13 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0020_conversation_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='communications.contact'),
        ),
    ]
