# Generated by Django 5.2.4 on 2026-08-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0021_alter_conversation_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsignature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='email_signatures/%Y/%m/', verbose_name='Imagen de firma'),
        ),
        migrations.AlterField(
            model_name='emailsignature',
            name='html_signature',
            field=models.TextField(blank=True, verbose_name='Firma HTML'),
        ),
        migrations.AlterField(
            model_name='emailsignature',
            name='plain_signature',
            field=models.TextField(blank=True, verbose_name='Firma Texto Plano'),
        ),
    ]
