# Generated by Django 5.2.4 on 2026-03-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workarea_userprofile_role_userprofile_work_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Permiso')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Código del Permiso')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('work_areas', models.ManyToManyField(blank=True, related_name='privileges', to='core.workarea', verbose_name='Áreas con este permiso')),
            ],
            options={
                'verbose_name': 'Privilegio',
                'verbose_name_plural': 'Privilegios',
            },
        ),
    ]
