# Generated by Django 5.2.4 on 2026-03-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_privilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Imagen de Perfil'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Modo Oscuro'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font_size',
            field=models.IntegerField(default=16, verbose_name='Tamaño de Fuente (px)'),
        ),
        migrations.DeleteModel(
            name='Privilege',
        ),
    ]
