# Generated by Django 5.2.4 on 2026-03-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_userrole_remove_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_roles', to='auth.group', verbose_name='Grupos asociados'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo (Active)'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Acceso al Staff (Staff status)'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superusuario (Superuser status)'),
        ),
    ]
