# Generated by Django 5.2.9 on 2026-01-03 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('invoices', '0002_remove_invoice_amount_remove_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.article'),
        ),
    ]
