# Generated by Django 5.2.9 on 2026-01-04 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='tpv.cashregister', verbose_name='Caja'),
        ),
    ]
