# Generated by Django 5.2.4 on 2026-03-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clienttag_client_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Dato Adicional'),
        ),
        migrations.AddField(
            model_name='client',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='client',
            name='cuit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='client',
            name='fiscal_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Fiscal'),
        ),
        migrations.AddField(
            model_name='client',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo en Empresa'),
        ),
    ]
