# Generated by Django 5.2.4 on 2026-03-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_additional_info_client_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Notas privadas visibles solo para usuarios del sistema', null=True, verbose_name='Notas Internas'),
        ),
    ]
